import { ValidationError } from "../errors";

export async function readJson(request: Request): Promise<unknown> {
  try {
    return await request.json();
  } catch {
    throw new ValidationError("Request body must be valid JSON");
  }
}

// Anonymous storefront identity: "guest-<uuid>", generated by the browser.
// It scopes a cart/wishlist to one browser; it is NOT authentication.
const CUSTOMER_ID = /^guest-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;

export function getCustomerId(request: Request): string {
  const value = request.headers.get("x-customer-id") ?? "";
  if (!CUSTOMER_ID.test(value)) {
    throw new ValidationError("X-Customer-Id header is missing or malformed");
  }
  return value;
}
